version: '3.8'
services:
  node:
    build: .
    volumes:
      - ./src:/flick/src
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    # env_file:
    #   - ./.env
    stdin_open: true